All variables are now quoted. Improved error reporting (errors to stderr & individual mktemp error detection)

diff --git a/postwhite b/postwhite
--- a/postwhite
+++ b/postwhite
@@ -63,83 +63,85 @@ if [ -s $config_file ] ; then
 	printf "\nReading options from %s...\n" "$config_file"
 	. "${config_file}"
 else
-	printf "\nCan't find %s. Exiting.\n\n" "$config_file"
+	>&2 printf "%s: Can't find %s. Exiting.\n" "$0" "$config_file"
 	exit 1
 fi
 
 # Create temporary files
 printf "\nCreating temporary files...\n"
 tmpBase=$(basename "$0")
-tmp1=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-tmp2=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-tmp3=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-tmp4=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-tmp5=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-if [ x"$enable_blacklist" = x"yes" ] ; then
-	blktmp1=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-	blktmp2=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-	blktmp3=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-	blktmp4=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
-	blktmp5=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
+
+if [ x"$enable_blacklist" = x"yes" ]; then
+	tmpPrefix="tmp blktmp"
+else
+	tmpPrefix="tmp"
 fi
-	if [ $? -ne 0 ]; then
-		printf "$0: Can't create temp files, exiting...\n"
-		exit 1
-	fi
+
+for p in $tmpPrefix; do
+	for i in 1 2 3 4 5; do
+		t="$(mktemp -q /tmp/"${tmpBase}".XXXXXX)"
+		if [ $? -ne 0 ]; then
+			>&2 printf "%s: Can't create temp files, exiting...\n" "$0"
+			cleanup
+			exit 1
+		fi
+		eval ${p}${i}="$t"
+	done
+done
 
 # Create IPv4 normalize function
 ip2int() {
     for i in 1 2 3 4 5; do
-        eval ip2int_${i}=$(echo "$1" | cut -s -d. -f$i)
+        eval ip2int_${i}="$(echo "$1" | cut -s -d. -f$i)"
     done
-    ip2int_valid_range=$((ip2int_1 | ip2int_2 | ip2int_3 | ip2int_4))
+    ip2int_valid_range="$((ip2int_1 | ip2int_2 | ip2int_3 | ip2int_4))"
     [ -z "$ip2int_5" ] && [ -n "$ip2int_1" ] && [ -n "$ip2int_2" ] && [ -n "$ip2int_3" ] && [ -n "$ip2int_4" ] && [ "$ip2int_valid_range" -ge 0 ] && [ "$ip2int_valid_range" -le 255 ] &&
-        printf "%d" $(((((((ip2int_1 << 8) | ip2int_2) << 8) | ip2int_3) << 8) | ip2int_4))
+        printf "%d" "$(((((((ip2int_1 << 8) | ip2int_2) << 8) | ip2int_3) << 8) | ip2int_4))"
 }
 
 int2ip() {
-    int2ip_ui32=$1; shift
+    int2ip_ui32="$1"; shift
     int2ip_ip=""
     [ -n "$int2ip_ui32" ] && [ "$int2ip_ui32" -ge 0 ] && [ "$int2ip_ui32" -le 4294967295 ] && for n in 1 2 3 4; do
-        int2ip_ip=$((int2ip_ui32 & 0xff))${int2ip_ip:+.}$int2ip_ip
-        int2ip_ui32=$((int2ip_ui32 >> 8))
+        int2ip_ip="$((int2ip_ui32 & 0xff))${int2ip_ip:+.}$int2ip_ip"
+        int2ip_ui32="$((int2ip_ui32 >> 8))"
     done
     printf "%s" "${int2ip_ip}"
 }
 
 network_v4() {
-    network_v4_ia=$(echo "$1" | cut -d/ -f1)
-    network_v4_netmask=$(echo "$1" | cut -d/ -f2-)
+    network_v4_ia="$(echo "$1" | cut -d/ -f1)"
+    network_v4_netmask="$(echo "$1" | cut -d/ -f2-)"
     if [ -n "$network_v4_netmask" ] && [ "$network_v4_netmask" -ge 0 ] && [ "$network_v4_netmask" -le 32 ]; then
-        network_v4_addr=$(ip2int $network_v4_ia);
-        network_v4_mask=$((0xffffffff << (32 - network_v4_netmask)));
-        if [ $network_v4_netmask -eq 32 ]; then
+        network_v4_addr="$(ip2int $network_v4_ia)"
+        network_v4_mask="$((0xffffffff << (32 - network_v4_netmask)))"
+        if [ "$network_v4_netmask" -eq 32 ]; then
             printf "%s" $(int2ip $((network_v4_addr & network_v4_mask)))
         else
-            printf "%s/%s" $(int2ip $((network_v4_addr & network_v4_mask))) $network_v4_netmask
+            printf "%s/%s" "$(int2ip $((network_v4_addr & network_v4_mask)))" "$network_v4_netmask"
         fi
     fi
 }
 
 network_v6() {
     # TODO
-    printf "%s" $1
+    printf "%s" "$1"
 }
 
 normalize_ip() {
 	# split by ":"
-	normalize_ip_type=$( echo $1 | cut -s -d\: -f1)
-	normalize_ip_value=$( echo $1 | cut -s -d\: -f2-)
+	normalize_ip_type="$( echo $1 | cut -s -d\: -f1)"
+	normalize_ip_value="$( echo $1 | cut -s -d\: -f2-)"
         normalize_ip_IP=""
 	if [ x"${normalize_ip_type}" = x"ip4" ] ; then
 		# check if is a CIDR
 		if expr "x${normalize_ip_value}" : "x.*/[0-9]*" > /dev/null; then
-			normalize_ip_IP=$(network_v4 "${normalize_ip_value}");
+			normalize_ip_IP="$(network_v4 "${normalize_ip_value}")"
 		else
-			normalize_ip_IP=$(network_v4 "${normalize_ip_value}/32");
+			normalize_ip_IP="$(network_v4 "${normalize_ip_value}/32")"
 		fi
 	elif [ x"${normalize_ip_type}" = x"ip6" ]; then
-		normalize_ip_IP=$(network_v6 "${normalize_ip_value}")
+		normalize_ip_IP="$(network_v6 "${normalize_ip_value}")"
 	fi
 	printf "%s" "$normalize_ip_IP"
 }
@@ -155,7 +157,7 @@ query_black_host() {
 
 # Create progress dots function
 show_dots() {
-	while ps $1 >/dev/null ; do
+	while ps "$1" >/dev/null ; do
 	printf "."
 	sleep 1
 	done
@@ -164,8 +166,8 @@ show_dots() {
 
 # Fix mode
 fix_invalid_ip() {
-	fix_invalid_ip_iptype=$( echo "$1" | cut -d\: -f1 )
-	fix_invalid_ip_ip=$(normalize_ip "$1")
+	fix_invalid_ip_iptype="$( echo "$1" | cut -d\: -f1 )"
+	fix_invalid_ip_ip="$(normalize_ip "$1")"
 	if [ -n "$fix_invalid_ip_ip" ]; then
 		if [ x"$fix_invalid_ip_iptype" = x"ip4" ]; then
 			printf "$(eval printf "%s" "\${${2}_line_v4}")" "$fix_invalid_ip_ip"
@@ -177,9 +179,9 @@ fix_invalid_ip() {
 
 # Remove mode
 remove_invalid_ip() {
-	remove_invalid_ip_iptype=$( echo "$1" | cut -d\: -f1 )
-	remove_invalid_ip_origip=$( echo "$1" | cut -d\: -f2- )
-	remove_invalid_ip_ip=$(normalize_ip "$1")
+	remove_invalid_ip_iptype="$( echo "$1" | cut -d\: -f1 )"
+	remove_invalid_ip_origip="$( echo "$1" | cut -d\: -f2- )"
+	remove_invalid_ip_ip="$(normalize_ip "$1")"
 	if [ x"$remove_invalid_ip_origip" = x"$remove_invalid_ip_ip" ]; then
 		if [ x"$remove_invalid_ip_iptype" = x"ip4" ]; then
 			printf "$(eval printf "%s" "\${${2}_line_v4}")" "$remove_invalid_ip_ip"
@@ -191,8 +193,8 @@ remove_invalid_ip() {
 
 # Keep mode
 keep_invalid_ip() {
-	keep_invalid_ip_iptype=$( echo "$1" | cut -d\: -f1 )
-	keep_invalid_ip_ip=$( echo "$1" | cut -d\: -f2- )
+	keep_invalid_ip_iptype="$( echo "$1" | cut -d\: -f1 )"
+	keep_invalid_ip_ip="$( echo "$1" | cut -d\: -f2- )"
 	if [ -n "$keep_invalid_ip_ip" ]; then
 		if [ x"$keep_invalid_ip_iptype" = x"ip4" ]; then
 			printf "$(eval printf "%s" "\${${2}_line_v4}")" "$keep_invalid_ip_ip"
@@ -211,37 +213,37 @@ printf "\nRecursively querying SPF records of selected whitelist mailers...\n"
 printf "\nQuerying webmail hosts...\n"
 
 for h in ${webmail_hosts}; do
-    $(query_host "${h}")
+    query_host "${h}"
 done
 
 printf "\nQuerying social network hosts...\n"
 
 for h in ${social_hosts}; do
-    $(query_host "${h}")
+    query_host "${h}"
 done
 
 printf "\nQuerying ecommerce hosts...\n"
 
 for h in ${commerce_hosts}; do
-    $(query_host "${h}")
+    query_host "${h}"
 done
 
 printf "\nQuerying bulk mail hosts...\n"
 
 for h in ${bulk_hosts}; do
-    $(query_host "${h}")
+    query_host "${h}"
 done
 
 printf "\nQuerying miscellaneous hosts...\n"
 
 for h in ${misc_hosts}; do
-    $(query_host "${h}")
+    query_host "${h}"
 done
 
 printf "\nQuerying custom hosts...\n"
           
 for h in ${custom_hosts}; do
-    $(query_host "${h}")
+    query_host "${h}"
 done
 
 if [ x"$include_yahoo" = x"yes" ] ; then
@@ -254,7 +256,7 @@ if [ x"$enable_blacklist" = x"yes" ] ; then
 	printf "\nQuerying blacklist hosts...\n"
 
 	for h in ${blacklist_hosts}; do
-	    $(query_black_host "${h}")
+	    query_black_host "${h}"
 	done
 fi
 
@@ -264,13 +266,13 @@ if [ x"$simplify" = x"yes" ]; then
 	printf "can take a LONG time if you have many mailers selected. Please be patient..."
 	
 	cat "${tmp1}" | sort -u | "${spftoolspath}"/simplify.sh > "${tmp2}" &
-	show_dots $!
+	show_dots "$!"
 
 	if [ x"$enable_blacklist" = x"yes" ] ; then
 		printf "\nSimplifying blacklist IP addresses already included in CIDR ranges. These calculations\n"
 	        printf "can take a LONG time if you have many mailers selected. Please be patient..."
 	        cat "${blktmp1}" | sort -u | "${spftoolspath}"/simplify.sh > "${blktmp2}" &
-	        show_dots $!
+	        show_dots "$!"
 	fi
 	
 	printf "\nIP address simplification complete.\n"
@@ -289,14 +291,14 @@ if [ x"$invalid_ip4" = x"fix" ] ; then
 	cat "${tmp2}" | while read ip; do
 		fix_invalid_ip "$ip" "permit"
 	done >> "${tmp3}" &
-	show_dots $!
+	show_dots "$!"
 
 	if [ x"$enable_blacklist" = x"yes" ] ; then
 		printf "\nFixing invalid blacklist IPv4 CIDRs..."
 		cat "${blktmp2}" | while read ip; do
 			fix_invalid_ip "$ip" "reject"
 		done >> "${blktmp3}" &
-	        show_dots $!
+	        show_dots "$!"
 	fi
 
 # If enabled, remove invalid CIDRs
@@ -305,14 +307,14 @@ elif [ x"$invalid_ip4" = x"remove" ] ; then
 	cat "${tmp2}" | while read ip; do
 		remove_invalid_ip "$ip" "permit"
 	done >> "${tmp3}" &
-	show_dots $!
+	show_dots "$!"
 
 	if [ x"$enable_blacklist" = x"yes" ] ; then
 		printf "\nRemoving invalid IPv4 CIDRs from blacklist..."
 		cat "${blktmp2}" | while read ip; do
 			remove_invalid_ip "$ip" "reject"
 		done >> "${blktmp3}" &
-		show_dots $!
+		show_dots "$!"
 	fi
 
 # If enabled, keep invalid CIDRs
@@ -321,14 +323,14 @@ elif [ x"$invalid_ip4" = x"keep" ] ; then
 	cat "${tmp2}" | while read ip; do
 		keep_invalid_ip "$ip" "permit"
 	done >> "${tmp3}" &
-	show_dots $!
+	show_dots "$!"
 
 	if [ x"$enable_blacklist" = x"yes" ] ; then
 		printf "\nKeeping invalid blacklist IPv4 CIDRs...\n"
 		cat "${blktmp2}" | while read ip; do
 			keep_invalid_ip "$ip" "reject"
 		done >> "${blktmp3}" &
-		show_dots $!
+		show_dots "$!"
 	fi
 fi
 
@@ -358,18 +360,21 @@ if [ x"$enable_blacklist" = x"yes" ] ; then
 fi
 
 # Remove temp files
-test -e "${tmp1}" && rm "${tmp1}"
-test -e "${tmp2}" && rm "${tmp2}"
-test -e "${tmp3}" && rm "${tmp3}"
-test -e "${tmp4}" && rm "${tmp4}"
-test -e "${tmp5}" && rm "${tmp5}"
-if [ x"$enable_blacklist" = x"yes" ] ; then
-	test -e "${blktmp1}" && rm "${blktmp1}"
-	test -e "${blktmp2}" && rm "${blktmp2}"
-	test -e "${blktmp3}" && rm "${blktmp3}"
-	test -e "${blktmp4}" && rm "${blktmp4}"
-	test -e "${blktmp5}" && rm "${blktmp5}"
-fi
+cleanup() {
+	test -e "${tmp1}" && rm "${tmp1}"
+	test -e "${tmp2}" && rm "${tmp2}"
+	test -e "${tmp3}" && rm "${tmp3}"
+	test -e "${tmp4}" && rm "${tmp4}"
+	test -e "${tmp5}" && rm "${tmp5}"
+	if [ x"$enable_blacklist" = x"yes" ] ; then
+		test -e "${blktmp1}" && rm "${blktmp1}"
+		test -e "${blktmp2}" && rm "${blktmp2}"
+		test -e "${blktmp3}" && rm "${blktmp3}"
+		test -e "${blktmp4}" && rm "${blktmp4}"
+		test -e "${blktmp5}" && rm "${blktmp5}"
+	fi
+}
+cleanup
 
 # Reload Postfix to pick up changes in whitelist
 if [ x"$reload_postfix" = x"yes" ]; then
