bypass lookups when 'b' doesn't resolve, and test if 'a' or 'b' should be increased

diff --git a/query_mailer_ovh b/query_mailer_ovh
--- a/query_mailer_ovh
+++ b/query_mailer_ovh
@@ -9,13 +9,13 @@
 # By Jesse Norell (https://github.com/jnorell)
 # and Steve Jenkins (https://www.stevejenkins.com/)
 
-version="1.1"
-lastupdated="16 April 2018"
+version="1.2"
+lastupdated="17 April 2018"
 
 whitelist_file="/etc/postfix/postscreen_ovh_whitelist.cidr"
 
 # set debug=true to display output as this script runs
-debug=true
+debug=false
 
 ###########################################################################
         
@@ -46,18 +46,41 @@ umask 022
 # create tmp file
 temp_file=$(mktemp --tmpdir ovh_hosts.XXXXXXXXXX)
 
-# clean up tmp file on exit
-trap "rm -f ${temp_file};" EXIT
+# clean up tmp file on exit unless debug=true
+[ "${debug}" = true ] || trap "rm -f ${temp_file};" EXIT
 
 debug "Querying outbound IP addresses. This could take a while...\n"
 
 # Query user-defined mailer range
+#
+# OVH uses the format: ${a}.mo${b}.mail-out.ovh.net;
+# not all valid "b" values are consecutive;
+# in testing, the mo${b}.mail-out.ovh.net level resolves to an address,
+# so for efficiency we'll skip any that don't resolve
 
-for a in {1..99};
-        do for b in {1..300};
-                do host ${a}.mo${b}.mail-out.ovh.net;
+for b in {1..300}; do
+    if ( host mo${b}.mail-out.ovh.net 2>&1 ); then
+        for a in {1..99}; do
+            host ${a}.mo${b}.mail-out.ovh.net 2>&1
         done;
+
+	: ${a++}
+
+        # test if 'a' should be increased
+        if ( host ${a}.mo${b}.mail-out.ovh.net 2>&1 ); then
+            echo "Note: ${a}mo${b}.mail-out.ovh.net resolves to an address," 1>&2
+            echo "you should edit this script and increase the max range for 'a'." 1>&2
+        fi
+    fi
 done > "${temp_file}"
+
+: ${b++}
+
+# test if 'b' should be increased
+if ( host mo${b}.mail-out.ovh.net 2>&1 >/dev/null ); then
+    echo "Note: mo${b}.mail-out.ovh.net resolves to an address," 1>&2
+    echo "you should edit this script and increase the max range for 'b'." 1>&2
+fi
 
 # Format queried hosts
 
@@ -70,6 +93,8 @@ grep 'has address' "${temp_file}" | awk '{print $4 " permit"}' | sort -uV  > "${
 debug "Restarting Postfix...\n"
 
 [ "${debug}" = true ] && postfix reload || postfix reload 2>/dev/null
+
+debug "Hostname lookups preserved in file: ${temp_file}\n"
 
 # All done!
 
